Avia/Avia.MVC/Models/Settings/ClientVM.cs

using System.ComponentModel.DataAnnotations;

namespace Avia.MVC.Models.Settings
{
    public class ClientVM
    {
        
        public int Id { get; set; }

        [Display(Name = "Имя")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Отчество")] 
        public string SecondName { get; set; }
    }
}

Avia/Avia.MVC/Models/Settings/CompanyVM.cs
using System.ComponentModel.DataAnnotations;

namespace Avia.MVC.Models.Settings
{
    public class CompanyVM
    {
        public int Id { get; set; }

        [Display(Name = "Процент")]
        [Required(ErrorMessage = "*")]
        public double Percent { get; set; }

        [Display(Name = "Название")]
        [Required(ErrorMessage = "*")]
        public string Name { get; set; }
    }
}

Avia/Avia.MVC/Controllers/SettingsController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Avia.BLL.Interfaces;
using Avia.Domain.Entyties;
using Avia.Domain.People;
using Avia.Domain.Repositories;
using Avia.MVC.Models.Settings;

namespace Avia.MVC.Controllers
{

    public class SettingsController : BaseController
    {
        public SettingsController(IUnitofWork db1, IServiceUser service) : base(service, db1: db1)
        {
        }


        #region Авиакомпании

        [HttpGet]
        public ActionResult Companies()
        {
            var list = Db.Companies.GetAll().ToList();
            return View(list);
        }
         
        [HttpGet]
        public ActionResult AddCompany()
        {
            ViewBag.Title = "Добавление авиакомпании";
            ViewBag.Action = "add";
            ViewBag.Caption = "Новая авиакомпания";
            return View("FormCompany");
        }

        [HttpPost]
        public ActionResult AddCompany(CompanyVM model)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(expression => expression.CreateMap<CompanyVM, Company>());
                var company = Mapper.Map<CompanyVM, Company>(model);
                Db.Companies.Create(company);
                Db.Save();
                return RedirectToAction("Companies");
            }
            return View("FormCompany", model);
        }

        
        [HttpGet]
        public ActionResult EditCompany(int id)
        {
            var company = Db.Companies.GetNoTrack(id);
            if (company == null) return RedirectToAction("Companies");

            ViewBag.Title = "Изменение авиакомпании";
            ViewBag.Caption = "Авикомпания";
            ViewBag.Action = "edit";
            Mapper.Initialize(ex => ex.CreateMap<Company, CompanyVM>());
            var model = Mapper.Map<CompanyVM>(company);

            return View("FormCompany", model);
        }

        [HttpPost]
        public ActionResult EditCompany(CompanyVM model)
        {
            if (ModelState.IsValid)
            {
                var company = Db.Companies.GetNoTrack(model.Id);

                if (company != null)
                {
                    company.Percent = model.Percent;
                    company.Name = model.Name;
                    Db.Companies.Update(company);
                    Db.Save();
                    return RedirectToAction("Companies");
                }
                ModelState.AddModelError("IdCompany", "Не найдена компания");
            }
            ViewBag.Action = "edit";
            return View("FormCompany", model);
        }

        #endregion


        #region Клиенты

        [HttpGet]
        public ActionResult Clients()
        {
            var clients = Db.Clients.GetAll().ToList(); 
            return View(clients);
        }

        
        [HttpGet]
        public ActionResult AddClient()
        {
            ViewBag.Title = "Добавление клиета";
            ViewBag.Action = "add";
            ViewBag.Caption = "Новый клиент";
            return View("FormClient");
        }

        [HttpPost]
        public ActionResult AddClient(ClientVM model)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(expression => expression.CreateMap<ClientVM, Client>());
                var client = Mapper.Map<Client>(model);
                Db.Clients.Create(client);
                Db.Save();
                return RedirectToAction("Clients");
            }
            return View("FormClient", model);
        }

        [HttpGet]
        public ActionResult EditClient(int id)
        {
            var client = Db.Clients.GetNoTrack(id);
            if (client == null) return RedirectToAction("Clients");

            ViewBag.Title = "Изменение клиета";
            ViewBag.Action = "edit";
            ViewBag.Caption = "Клиент";
            Mapper.Initialize(ex => ex.CreateMap<Client, ClientVM>());
            var model = Mapper.Map<ClientVM>(client);

            return View("FormClient", model);
        }

        [HttpPost]
        public ActionResult EditClient(ClientVM model)
        {
         
            if (ModelState.IsValid)
            {
                var client = Db.Clients.GetNoTrack(model.Id);

               if(client==null)  ModelState.AddModelError("Id","Не найден клиент");

                Mapper.Initialize(expression => expression.CreateMap<ClientVM, Client>());

                var newClient = Mapper.Map(model, client);

                Db.Clients.Update(newClient);
                Db.Save();
                return RedirectToAction("Clients");
            }
            return View("FormClient");
        }

         
        #endregion


    }
}

Avia/Avia.MVC/Views/Settings/Clients.cshtml
@model List<Avia.Domain.People.Client>

@{
    ViewBag.Title = "Список клиентов";
}

<div class="box">
    <div class="box-header with-border col-md-offset-10">
        <a href="@Url.Action("AddClient", "Settings")" class="btn btn-success"><span class="fa fa-user-plus"></span>   Добавить клиента</a>

    </div>

    @if (Model.Count > 0)
    {
    <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Фамилия</th>
                        <th>Имя</th>
                        <th>Отчество</th>
                        <th class="text-bold">Управление</th>
                    </tr>

                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>
                                @(i + 1)
                            </td>
                            <td>@Model[i].FirstName</td>
                            <td>@Model[i].Name</td>
                            <td>@Model[i].SecondName</td>
                            <td>
                                <div>
                                    <a href="@Url.Action("EditClient", "Settings", new {id = Model[i].Id})" class="btn btn-primary">
                                        <span class="fa fa-edit"></span> Изменить
                                    </a>
                                </div>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    <!-- /.box-body -->

            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
    }

</div>

Avia/Avia.MVC/Views/Settings/Companies.cshtml
@model List<Avia.Domain.Entyties.Company>

@{
    ViewBag.Title = "Авиа компании";
}


<div class="box">
    <div class="box-header with-border col-md-offset-10">
        <a href="@Url.Action("AddCompany", "Settings")" class="btn btn-success"><span class="fa fa-plus"></span>   Добавить компанию</a>

    </div>

    @if (Model.Count > 0)
    {
    <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Название</th>
                        <th>Проценты</th>
                        <th>Проценты</th>
                        <th class="text-bold">Управление</th>
                    </tr>

                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@Model[i].Name</td>
                            <td>
                                <div class="progress progress-xs">
                                    <div class="progress-bar @{
                                        if (Model[i] != null)
                                        {
                                            if(Model[i].Percent <2) { @MvcHtmlString.Create("progress-bar-red")}
                                            else
                                            if(Model[i].Percent <4) { @MvcHtmlString.Create("	progress-bar-yellow")}
                                            else
                                                 if(Model[i].Percent <7) { @MvcHtmlString.Create("	progress-bar-aqua")}
                                            else
                                                 if(Model[i].Percent <100) { @MvcHtmlString.Create("	progress-bar-green")}
                                        }
                                                             }" style="width: @Model[i].Percent%"></div>
                                </div>
                            </td>
                            <td><span class="badge @{
                                        if (Model[i] != null)
                                        {
                                            if(Model[i].Percent <2) { @MvcHtmlString.Create(" bg-red")}
                                            else
                                            if(Model[i].Percent <4) { @MvcHtmlString.Create("bg-yellow")}
                                            else
                                                 if(Model[i].Percent <7) { @MvcHtmlString.Create("bg-light-blue")}
                                            else
                                                 if(Model[i].Percent <100) { @MvcHtmlString.Create("bg-green")}
                                        }
                                                             }">@Model[i].Percent%</span></td>
                            <td>
                                <div>
                                    <a href="@Url.Action("EditCompany", "Settings", new {id = Model[i].Id})" class="btn btn-primary">
                                        <span class="fa fa-edit"></span> Изменить
                                    </a>
                                </div>

                            </td>
                        </tr>
    }


                </tbody>
            </table>
        </div>
    <!-- /.box-body -->

        <div class="box-footer clearfix">
            <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
            </ul>
        </div>
    }

</div>

Avia/Avia.MVC/Views/Settings/FormClient.cshtml
@using Avia.MVC.Helpers
@model Avia.MVC.Models.Settings.ClientVM

<section class="content">
    <div class="box @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("box-warning");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("box-success");
                                         }">
        @{
            string action;

            if (ViewBag.Action == "edit")
            {
                action = "EditClient";
            }
            else
            {
                action = "AddClient";
            }

            using (Html.BeginForm(action, "Settings", FormMethod.Post))
            {
                <div class="box-header with-border">
                    <h3 class="box-title @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("text-yellow");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("text-green");
                                         } ">
                        @ViewBag.Title
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Скрыть">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Закрыть">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">

                    <input type="hidden" id="Id" name="Id" value="@{ if (Model == null)
                        {
                                                       @MvcHtmlString.Create("0");
                        }
                        else
                        {@MvcHtmlString.Create(Model.Id.ToString());}
                             }" />
                    @Html.AntiForgeryToken()
                    <div class="col-lg-3 col-md-offset-4">
                        @Html.CTextBoxFor(d => d.FirstName, "название")
                        @Html.CTextBoxFor(d => d.Name, "название")
                        @Html.CTextBoxFor(d => d.SecondName, "название")
                    </div>
                </div>
            <!-- /.box-body -->
                <div class="box-footer">
                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-5">
                            <button type="submit" class="btn @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("btn-warning");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("btn-success");
                                         } ">
                                <span class="glyphicon glyphicon-saved"></span>  Сохранить
                            </button>

                        </div>
                    </div>
                </div>
    }
        }
        <!-- /.box-footer-->
    </div>
</section>

Avia/Avia.MVC/Views/Settings/FormCompany.cshtml
@using Avia.MVC.Helpers
@model Avia.MVC.Models.Settings.CompanyVM


<section class="content">
    <div class="box @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("box-warning");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("box-success");
                                         }">
        @{
            string action;

            if (ViewBag.Action == "edit")
            {
                action = "EditCompany";
            }
            else
            {
                action = "AddCompany";
            }

            using (Html.BeginForm(action, "Settings", FormMethod.Post))
            {
                <div class="box-header with-border">
                    <h3 class="box-title @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("text-yellow");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("text-green");
                                         } ">
                        @ViewBag.Caption
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Скрыть">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Закрыть">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    
                    <input type="hidden" id="Id" name="Id" value="@{ if (Model == null)
                        {
                                                       @MvcHtmlString.Create("0");
                        }
                        else
                        {@MvcHtmlString.Create(Model.Id.ToString());}
                             }" />
                    @Html.AntiForgeryToken()
                    <div class="col-lg-3 col-md-offset-4">
                        @Html.CTextBoxFor(d => d.Name, "название")

                        @Html.CTextBoxForInputGroup(m => m.Percent, "процент", "", "%")

                    </div>
                </div>
            <!-- /.box-body -->
                <div class="box-footer">
                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-5">
                            <button type="submit" class="btn @if (ViewBag.Action == "edit")
                                         {
                                             @MvcHtmlString.Create("btn-warning");
                                         }
                                         else
                                         {
                                             @MvcHtmlString.Create("btn-success");
                                         } ">
                                <span class="glyphicon glyphicon-saved"></span>  Сохранить
                            </button>

                        </div>
                    </div>
                </div>
    }
        }
        <!-- /.box-footer-->
    </div>
</section>