Avia/Avia.MVC/Controllers/ReportController.cs
using System.Web.Mvc;
using Avia.BLL.Interfaces;
using Avia.MVC.Models.Roport;

namespace Avia.MVC.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly IDaylyReport _daylyReport;

        public ReportController(IDaylyReport daylyReport)
        {
            _daylyReport = daylyReport; 
        }


        public ActionResult ReportDay()
        {
            var model = new ReportDayVM();
            _daylyReport.MakeReport();
            model.SummaryCredited = _daylyReport.SummaryCredited;
            model.SummaryRefunded = _daylyReport.SummaryRefunded;
            model.SummarySalled = _daylyReport.SummarySalled;
            model.CreditTickets = _daylyReport.GetSalledOnCreditTickets();
            model.PayTickets = _daylyReport.GetSoldTickets();
            model.RefundTickets = _daylyReport.GetRefundTickets();
            model.Cash = _daylyReport.GetCash();
            return View(model);
        }

        public ActionResult CloseReportToDay()
        {
            _daylyReport.Close();
            return RedirectToAction("Index", "Home");
        }
    }
}

Avia/Avia.MVC/Views/Report/ReportDay.cshtml
@model Avia.MVC.Models.Roport.ReportDayVM

@{
    ViewBag.Title = "Отчет на сегодня";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (@Html.BeginForm("CloseReportToDay", "Report", FormMethod.Post))
{
    <div class="header">
        <div class="warning">
            <h4>
                 Итого в кассе: @Model.Cash сом.
            </h4>
        </div>
        <div class="text-right">
            <button type="submit" class="btn btn-lg btn-success">Закрыть кассу</button>
        </div>
    </div>
}

    <div class="nav-tabs-justified">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#SalleTickets" data-toggle="tab">Проданные</a></li>
            <li><a href="#CreditTickets" data-toggle="tab">Проданные в долг</a></li>
            <li><a href="#RefundTickets" data-toggle="tab">Возвращенные</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="SalleTickets">
                @if (Model.PayTickets.Any())
            {
            <table class="table table-bordered table-hover table-striped">
                @{
                        decimal itogAv = 0;
                        decimal pay = 0;
                }
                <tr>
                    <td>Id</td>
                    <td>Номер билета</td>
                    <td>Ф.И.О. клиента</td>
                    <td>Итого в а/к</td>
                    <td>Оплата пассажира</td>
                </tr>



                @foreach (var ticket in Model.PayTickets)
                    {
                        itogAv += ticket.ItogoAv;
                        pay += ticket.PayPass;
                    <tr class="success">
                        <td>@ticket.Id</td>
                        <td>@ticket.Number</td>
                        <td>@ticket.Passanger</td>
                        <td>@ticket.ItogoAv</td>
                        <td>@ticket.PayPass</td>
                    </tr>
                    }
                <tr class="text-bold ">
                    <td colspan="3" class="text-center">
                        Итого:
                    </td>
                    <td>
                        @itogAv
                    </td>
                    <td>
                        @pay
                    </td>
                </tr>
            </table>
            }
            </div>

            <div class="tab-pane  " id="CreditTickets">
                @if (Model.CreditTickets.Any())
            {

            <table class="table table-bordered table-hover table-striped">
                <tr>
                    <td>Id</td>
                    <td>Номер билета</td>
                    <td>Ф.И.О. клиента</td>
                    <td>Итого в а/к</td>
                    <td>Цена билета</td>
                    <td>Оплата пассажира</td>
                    <td>Долг</td>
                </tr>
                @{
                        decimal rItogAv = 0;
                        decimal costTicket = 0;
                    decimal payPass = 0;
                    decimal credit = 0;
                }
                @foreach (var ticket in Model.CreditTickets)
                {

                    rItogAv += ticket.ItogoAv;
                    costTicket += ticket.PayPass;
                    payPass += ticket.PayPass - ticket.CreditAmount;
                    credit += ticket.CreditAmount;
                    <tr class="danger">
                        <td>@ticket.Id</td>
                        <td>@ticket.Number</td>
                        <td>@ticket.Passanger</td>
                        <td>@ticket.ItogoAv</td>
                        <td>@ticket.PayPass</td>
                        <td>@Html.Raw(ticket.PayPass - ticket.CreditAmount)</td>
                        <td>@ticket.CreditAmount</td>
                        
                    </tr>

                    }

                <tr class="text-bold ">
                    <td colspan="3" class="text-center">
                        Итого:
                    </td>
                    <td>
                        @rItogAv
                    </td>
                    <td>
                        @costTicket
                    </td>
                    <td>
                        @payPass
                    </td>
                    <td>
                        @credit
                    </td>
                </tr>
            </table>
            }
            </div>


            <div class="tab-pane " id="RefundTickets">

                @if (Model.RefundTickets.Any())
            {

            <table class="table table-bordered table-hover table-striped">
                <tr>
                    <td>Id</td>
                    <td>Номер билета</td>
                    <td>Ф.И.О. клиента</td>
                    <td>Итого в а/к</td>
                    <td>Оплата пассажира</td>
                </tr>
                @{
                        decimal rItogAv = 0;
                        decimal Rpay = 0;
                }
                @foreach (var ticket in Model.RefundTickets)
                    {

                        rItogAv += ticket.Ticket.ItogoAv;
                        Rpay += ticket.Ticket.PayPass;
                    <tr class="danger">
                        <td>@ticket.Id</td>
                        <td>@ticket.Ticket.Number</td>
                        <td>@ticket.Ticket.Passanger</td>
                        <td>@ticket.Ticket.ItogoAv</td>
                        <td>@ticket.Ticket.PayPass</td>
                    </tr>

                    }

                <tr class="text-bold ">
                    <td colspan="3" class="text-center">
                        Итого:
                    </td>
                    <td>
                        @rItogAv
                    </td>
                    <td>
                        @Rpay
                    </td>
                </tr>
            </table>
            }
            </div>


        </div>

    </div>
   